INSERT INTO products (NAME, PRICE) VALUES ('Mike', 75);
INSERT INTO products (NAME, PRICE) VALUES ('Tom', 50);
INSERT INTO products (NAME, PRICE) VALUES ('Tim', 200);
INSERT INTO products (NAME, PRICE) VALUES ('John', 100);
INSERT INTO products (NAME, PRICE) VALUES ('Bob', 150);